[package]
name = "coe-rs"
version = "0.1.0"
edition = "2021"
authors = ["sarah <>"]
description = "Type coercion"
readme = "README.md"
repository = "https://github.com/sarah-ek/coe-rs/"
license = "MIT"
keywords = ["metaprogramming", "generics", "specialization"]

[lib]
name = "coe"

[dependencies]
